#!/bin/bash

echo "Attempting to install all publicly available packs found in www.keil.com/pack/keil.vidx"
echo "Warning: this should only be used from time to time (possibly before releases) because it'll download dozens of GB of files"

mkdir -p tmp
cd tmp

wget https://www.keil.com/pack/index.pidx
grep '<pdsc' index.pidx | sed -e 's/.*url="/ /' -e 's/" vendor="/ /' -e 's/" name="/ /' -e 's/" version="/ /' -e 's/".*//' | awk '{print $1$2"."$3"."$4".pack"}' > packs_urls

for u in `cat packs_urls`
do
	echo installing $u
	../build/cpackget -v pack add --agree-embedded-license $u
done
