name: check copyright
on:
  pull_request:
    paths:
      - '.github/workflows/check-copyright.yml'
      - '.pre-commit-config.yaml'
      - 'scripts/check_copyright_notice.py'
      - '**/*.go'
      - '!**/docs/**/*'
      - '!**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  copyright:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout devtools
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check copyright notice
        run: |
          pip install \
            pre-commit \
            comment-parser>=1.2.3
          pre-commit run --all-files
