name: Release

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/release.yml
      - ./scripts/release_notes
      - .goreleaser.yml
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  build-and-verify:
    permissions:
      contents: read
      actions: write
    uses: Open-CMSIS-Pack/workflows-and-actions-collection/.github/workflows/build-and-verify.yml@v3.0.1
    with:
      program: cpackget
      test-matrix: '[{"platform":"windows-2022","arch":"amd64"},{"platform":"ubuntu-24.04","arch":"amd64"},{"platform":"macos-14","arch":"amd64"},{"platform":"ubuntu-24.04","arch":"arm64"}]'
      go-version-file: ./go.mod
      enable-qlty-coverage: false

  goreleaser:
    needs: [build-and-verify]
    permissions:
      contents: write
      actions: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Download test results
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: test-results-*
          path: testreport/

      - name: Zip test reports
        run: |
          zip -r testreport.zip testreport

      - name: Attach test reports to release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: testreport.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Generate release notes
        run: |
          ./scripts/release_notes > /tmp/RELEASE_NOTES

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: latest
          args: release ${{ github.event_name != 'push' && '--snapshot' || '' }} --clean --release-notes=/tmp/RELEASE_NOTES
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
